app/config/routes.rb
CaneyWebsite::Application.routes.draw do
  resources :recipes do
  resources :comments
  end

  root :to => 'recipes#index'

end

app/app/models/comment.rb
class Comment < ActiveRecord::Base
  # Foreign Key
  belongs_to :recipe
end

app/app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :author, :ingredients, :directions

  #1 to many
  has_many :comments, :dependent => :destroy
end

app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # How the website handles a new comment
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.create(params[:comment])
    redirect_to recipe_path(@recipe)
  end

  # How the website deletes a comment
  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    @comment = @recipe.comments.find(params[:id])
    @comment.destroy
    redirect_to recipe_path(@recipe)
  end
end

app/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # GET /recipes
  # GET /recipes.xml
  def index
    @recipes = Recipe.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recipes }
    end
  end

  # GET /recipes/1
  # GET /recipes/1.xml
  def show
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/new
  # GET /recipes/new.xml
  def new
    @recipe = Recipe.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recipe }
    end
  end

  # GET /recipes/1/edit
  def edit
    @recipe = Recipe.find(params[:id])
  end

  # POST /recipes
  # POST /recipes.xml
  def create
    @recipe = Recipe.new(params[:recipe])

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to(@recipe, :notice => 'Recipe was successfully created.') }
        format.xml  { render :xml => @recipe, :status => :created, :location => @recipe }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipes/1
  # PUT /recipes/1.xml
  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        format.html { redirect_to(@recipe, :notice => 'Recipe was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipe.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.xml
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to(recipes_url) }
      format.xml  { head :ok }
    end
  end
end

app/app/helpers/application_helper.rb
module ApplicationHelper
end

app/app/helpers/recipes_helper.rb
module RecipesHelper
end

app/app/views/comments/_comment.html.erb
<!-- Partial for displaying a comment -->

<p>
  <b>Comment:</b>
  <%= comment.content %>
</p>

<p>
  <%= link_to 'Delete Comment', [comment.recipe, comment],
              :confirm => 'Are you sure?',
              :method => :delete %>
</p>

app/app/views/comments/_form.html.erb
<!-- form used to add a comment -->

<%= form_for([@recipe, @recipe.comments.build]) do |f| %>
<div class="field">
  <%= f.text_area :content %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/app/views/layouts/_header.html.erb
<!-- defines the header, which is present on every page -->

<header>
  <% cookbook_logo = image_tag("cookbook_logo.png", :alt => "Sample App", :class => "round") %>
  <%= link_to cookbook_logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
    </ul>
  </nav>
</header>

app/app/views/layouts/_stylesheets.html.erb
<!-- links to style sheets under public/stylesheets -->

<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<%= stylesheet_link_tag 'caney_website', :media => 'screen' %>

app/app/views/layouts/application.html.erb
<!-- basic format for the pages -->

<!DOCTYPE html>
<html>
<head>
  <title>Recipe Website</title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
    </div>
</body>
</html>

app/app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :directions %><br />
    <%= f.text_area :directions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% @recipes.each do |recipe| %>
  <tr>
    <td><%= link_to recipe.name, recipe %></td>
  </tr>
<% end %>
</table>

<br />

<!-- link to add a new recipe to the websites -->
<%= link_to 'New Recipe', new_recipe_path, :class => 'addrecipe_button round' %>

app/app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/app/views/recipes/show.html.erb
<!-- displays the recipe and any comments by the user -->

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recipe.name %>
</p>

<p>
  <b>Author:</b>
  <%= @recipe.author %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @recipe.ingredients %>
</p>

<p>
  <b>Directions:</b>
  <%= @recipe.directions %>
</p>

<!-- add a comment, connects to comments/form partial -->
<h3>Add a comment:</h3>
<%= render "comments/form" %>

<br />

<!-- displays comments -->
<h3>Comments</h3>
<%= render @recipe.comments %>


<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>